$(document).ready(function(){
  $("#income-control").click(function(){
    $("#income-area").toggleClass("hide");
  });
  $("#registration-control").click(function(){
    $("#registration-area").toggleClass("hide");
  });
  $("#repay-control").click(function(){
    $("#repay-area").toggleClass("hide");
  });
  $("#birthday-control").click(function(){
    $("#birthday-area").toggleClass("hide");
  });
  $("#student-day-off-control").click(function(){
    $("#student-day-off-area").toggleClass("hide");
  });
  $("#employee-day-off-control").click(function(){
    $("#employee-day-off-area").toggleClass("hide");
  });
});